### ISSUE TITLE
some bug about "search folder"

### ISSUE THREAD

**Issue by bytimer** [TheZoc/EverythingDopusCLI#3] opened 2023-05-18 02:50 UTC
Current path is _**C:\Program Files**_ 
use the button，input _**exe**_ cilck **search folder** ： the results will = using everything directly to search _**"C:\Program Files" exe**_ ，may contain _**C:\Program Files (x86**_)
![image](https://github.com/TheZoc/EverythingDopus/assets/107342420/72655c85-02e3-403c-b291-38040bf83429)

The proper search text should be : `"C:\Program Files\" exe`
path need a \ at the end .
![image](https://github.com/TheZoc/EverythingDopus/assets/107342420/c40e7d35-9982-48cc-9582-6c1644d30843)

**Comment by bytimer** [comment] 2023-05-18 03:26
While using ed.exe directly，command :  **_ed C:\Program Files\ exe_**   will be equal to below 
![image](https://github.com/TheZoc/EverythingDopus/assets/107342420/b638ed5c-33fa-4d81-bd2c-d77dd1fc0528)

command : `ed "C:\Program Files\" exe`  ，result is 0
![image](https://github.com/TheZoc/EverythingDopus/assets/107342420/2c3d6292-e9a3-47ab-bbdc-63cf6ef024c4)

![image](https://github.com/TheZoc/EverythingDopus/assets/107342420/d8b1a894-f013-4541-841f-ef5d78d0efeb)


the proper command should be：`ed "C:\Program Files\\" exe`  , path need two \\\ at the end
![image](https://github.com/TheZoc/EverythingDopus/assets/107342420/bb80f1cd-62b9-4a8e-a6b6-445acda29c7d)

![image](https://github.com/TheZoc/EverythingDopus/assets/107342420/b2df0a5f-e7f7-4a8c-9b8a-1bcb45d1e3ed)

**Comment by bytimer** [comment] 2023-05-18 03:46
here is good modify
`"\\\\\" "`

`	case 2: // Search local folder only
		searchString = "\"" + scriptCmdData.func.sourcetab.path + "\\\\\" " + dlg.Control("cmbSearch").label;`

**Comment by bytimer** [comment] 2023-05-18 03:49
add a line，will be better 
`dlg.window = scriptCmdData.func.sourcetab;`

![image](https://github.com/TheZoc/EverythingDopus/assets/107342420/ad364f5c-911b-45e9-bacd-c1dfb541918c)

**Comment by TheZoc** [comment] 2023-05-18 09:51
@Sanhuaitang That bug was fixed in a9cc0569cace72067a26d6c1a31aa942c6c8b239 - it should work without modifying the script :)

![image](https://github.com/TheZoc/EverythingDopus/assets/924927/cdd23807-6ab1-4487-9bf8-65e341b06133)


Please, try again and let me know how it goes

**Comment by bytimer** [comment] 2023-05-18 11:34
> 

 quotes have been fixed.
but `path with space `   is not fixed
search folder `C:\Program Files`  ，the result will still contain files in `C:\Program Files (x86)`
the correct path string is `"C:\Program Files\"` , this means the string must endwith ' \\' , and must be  enclosed in quotes

**Comment by TheZoc** [comment] 2023-05-18 11:44
Enclosing the path with spaces in quotes seems to work fine in the latest version (v2.0 beta 2)

![image](https://github.com/TheZoc/EverythingDopus/assets/924927/d5bb5635-2c08-4262-b31c-59862f7841f5)


Can you provide reproduction steps with the (unmodified) v2.0 beta2, using the command line?

**Comment by bytimer** [comment] 2023-05-18 11:51
I found this：in root directory  c:\  ,  scriptCmdData.func.sourcetab.path = `c:\`
but  in a folder，C:\Windows ， scriptCmdData.func.sourcetab.path = `C:\Windows`  **(not end with a ' \\' )**

![image](https://github.com/TheZoc/EverythingDopus/assets/107342420/8f54f7d6-9003-4d6e-a12a-b494e89eae38)
![image](https://github.com/TheZoc/EverythingDopus/assets/107342420/4b57a961-5025-4972-a098-dedd24303186)
![image](https://github.com/TheZoc/EverythingDopus/assets/107342420/653acdd0-d048-422f-8f58-22a7f1d74f3b)
![image](https://github.com/TheZoc/EverythingDopus/assets/107342420/94ec708e-82fe-4f82-88a2-7e726481112d)
![image](https://github.com/TheZoc/EverythingDopus/assets/107342420/811512a0-5c33-4393-9c7a-0931640e2297)

**Comment by bytimer** [comment] 2023-05-18 11:55
![image](https://github.com/TheZoc/EverythingDopus/assets/107342420/71271dda-fe35-4d92-b96b-95d43537dc77)

![image](https://github.com/TheZoc/EverythingDopus/assets/107342420/c104bc1d-e014-4f40-adc7-ead18e2430e8)
I dont know why
sorry for my poor English....

end with two `\\`
![image](https://github.com/TheZoc/EverythingDopus/assets/107342420/28fbed29-ebc5-41ec-b77a-b80ec0626820)

**Comment by TheZoc** [comment] 2023-05-18 12:02
I'm not a native English speaker either, don't worry 🙂 

This seems to be quite the odd Unicode issue. Can you copy and paste that command line instruction from your console (don't try typing it directly here, use copy and paste) here, please?

I suspect that since I see that the quotes are tilted forward and that could be causing trouble.

**Comment by bytimer** [comment] 2023-05-18 12:03
OK , copy from cmd line 
`ed "C:\Program Files\\" exe`

**Comment by bytimer** [comment] 2023-05-18 12:11
code below work for me:
`		case 2: // Search local folder only

		var currentPath = scriptCmdData.func.sourcetab.path+"";

		currentPath = currentPath.replace(/\\+$/, "");

		searchString = "\"" + currentPath + "\\\\\" " + dlg.Control("cmbSearch").label;

		LogMessage("Search Folder Pressed - searchString: " + searchString);

		break; `

**Comment by TheZoc** [comment] 2023-05-18 12:29
@Sanhuaitang I appreciate that you got it working with a script hack :)
I don't understand why the command line utility fails on your pc, but works on mine.
Even worse, if I use the command line you sent me (`ed "C:\Program Files\\" exe`), it behaves the same as `ed "C:\Program Files" exe`

I still suspect this is related to regional settings and windows languages.

Are you happy with your solution, or do you want me to investigate further and send you more questions?
I'll probably need to make an auxiliary/utility build to dump some of the memory contents to check if something is changed while running from program if that's the case 🙁

**Comment by bytimer** [comment] 2023-05-18 14:04
Thanks for your hard and good work!
Though I still hope you could solve this problem, and not need script hack.

I have enhanced the script function，like below
![image](https://github.com/TheZoc/EverythingDopus/assets/107342420/893847d5-fa53-4ecc-90cd-9cfdbdd4eb22)

**Comment by TheZoc** [comment] 2023-05-18 21:43
@Sanhuaitang Sorry, today was a long day :(

I quickly hacked together an utility you can see here: 4adf74e67be0db52ffc9a108ca71bde2a0edc4db

[EverythingDopus-x64-UNICODE-UTILITY.zip](https://github.com/TheZoc/EverythingDopus/files/11511775/EverythingDopus-x64-UNICODE-UTILITY.zip)

Run it with the problematic string (it should be `ed "C:\Program Files\" exe` ) and please provide me with the output :)
(Do not send a screenshot, send the text output. I don't want to type all of that manually 😅 )

Hopefully this will help us get closer to the solution


This is what I get when I run locally:
```
GetCommandLine TCHAR: "D:\GitHub\EverythingDopus\x64\Debug\ed.exe" "C:\Program Files\\" exe
0022 0044 003A 005C 0047 0069 0074 0048 0075 0062 005C 0045 0076 0065 0072 0079 0074 0068 0069 006E 0067 0044 006F 0070 0075 0073 005C 0078 0036 0034 005C 0044 0065 0062 0075 0067 005C 0065 0064 002E 0065 0078 0065 0022 0020 0022 0043 003A 005C 0050 0072 006F 0067 0072 0061 006D 0020 0046 0069 006C 0065 0073 005C 005C 0022 0020 0065 0078 0065

GetCommandLine TCHAR to bytes: "D:\GitHub\EverythingDopus\x64\Debug\ed.exe" "C:\Program Files\\" exe
0022 0044 003A 005C 0047 0069 0074 0048 0075 0062 005C 0045 0076 0065 0072 0079 0074 0068 0069 006E 0067 0044 006F 0070 0075 0073 005C 0078 0036 0034 005C 0044 0065 0062 0075 0067 005C 0065 0064 002E 0065 0078 0065 0022 0020 0022 0043 003A 005C 0050 0072 006F 0067 0072 0061 006D 0020 0046 0069 006C 0065 0073 005C 005C 0022 0020 0065 0078 0065

===================

argv_quoted TCHAR:
[0] D:\GitHub\EverythingDopus\x64\Debug\ed.exe
0044 003A 005C 0047 0069 0074 0048 0075 0062 005C 0045 0076 0065 0072 0079 0074 0068 0069 006E 0067 0044 006F 0070 0075 0073 005C 0078 0036 0034 005C 0044 0065 0062 0075 0067 005C 0065 0064 002E 0065 0078 0065
[1] "C:\Program Files\"
0022 0043 003A 005C 0050 0072 006F 0067 0072 0061 006D 0020 0046 0069 006C 0065 0073 005C 0022
[2] exe
0065 0078 0065

===================

argv_quoted TCHAR to bytes:

[0] D:\GitHub\EverythingDopus\x64\Debug\ed.exe
0044 003A 005C 0047 0069 0074 0048 0075 0062 005C 0045 0076 0065 0072 0079 0074 0068 0069 006E 0067 0044 006F 0070 0075 0073 005C 0078 0036 0034 005C 0044 0065 0062 0075 0067 005C 0065 0064 002E 0065 0078 0065
[1] "C:\Program Files\"
0022 0043 003A 005C 0050 0072 006F 0067 0072 0061 006D 0020 0046 0069 006C 0065 0073 005C 0022
[2] exe
0065 0078 0065

===================

searchString TCHAR: "C:\Program Files\" exe
0022 0043 003A 005C 0050 0072 006F 0067 0072 0061 006D 0020 0046 0069 006C 0065 0073 005C 0022 0020 0065 0078 0065

searchString TCHAR to bytes: "C:\Program Files\" exe
0022 0043 003A 005C 0050 0072 006F 0067 0072 0061 006D 0020 0046 0069 006C 0065 0073 005C 0022 0020 0065 0078 0065
```

**Comment by bytimer** [comment] 2023-05-19 01:35
`GetCommandLine TCHAR: ed  "C:\Program Files\\" exe
0065 0064 0020 0020 0022 0043 003A 005C 0050 0072 006F 0067 0072 0061 006D 0020 0046 0069 006C 0065 0073 005C 0022 0020 0065 0078 0065

GetCommandLine TCHAR to bytes: ed  "C:\Program Files\\" exe
0065 0064 0020 0020 0022 0043 003A 005C 0050 0072 006F 0067 0072 0061 006D 0020 0046 0069 006C 0065 0073 005C 0022 0020 0065 0078 0065

===================

argv_quoted TCHAR:
[0] ed
0065 0064
[1] "C:\Program Files"" exe
0022 0043 003A 005C 0050 0072 006F 0067 0072 0061 006D 0020 0046 0069 006C 0065 0073 0022 0022 0020 0065 0078 0065

===================

argv_quoted TCHAR to bytes:

[0] ed
0065 0064
[1] "C:\Program Files"" exe
0022 0043 003A 005C 0050 0072 006F 0067 0072 0061 006D 0020 0046 0069 006C 0065 0073 0022 0022 0020 0065 0078 0065

===================

searchString TCHAR: "C:\Program Files"" exe
0022 0043 003A 005C 0050 0072 006F 0067 0072 0061 006D 0020 0046 0069 006C 0065 0073 0022 0022 0020 0065 0078 0065

searchString TCHAR to bytes: "C:\Program Files\"" exe
0022 0043 003A 005C 0050 0072 006F 0067 0072 0061 006D 0020 0046 0069 006C 0065 0073 0022 0022 0020 0065 0078 0065
C:\Program Files\GPSoftware\Directory Opus\Extools\EverythingDopus>
`

**Comment by bytimer** [comment] 2023-05-19 01:42
sorry， **add code** doesn't work for me，look at screenshot

![image](https://github.com/TheZoc/EverythingDopus/assets/107342420/a7438e76-f394-494c-a98e-db723e78a4b1)

**Comment by TheZoc** [comment] 2023-05-19 23:23
This was slightly trickier than expected, but I'm glad the utility actually helped with this issue.

Try this version: https://github.com/TheZoc/EverythingDopus/releases/tag/v2.0-beta3

Apparently the quotes are handled differently when passed through cmd and powershell.
This should make it mostly consistent between the two.
Powershell has a quirk when combining tons of backslashes and quotes, there's no valid path that require such weird combination :)

Please, let me know if it works for you now

**Comment by bytimer** [comment] 2023-05-20 07:11
when sourcepath is `C:\Program Files` ，the final command in the script  log will be：
`ed.exe "C:\Program Files" exe`
and its result will still contain files in `C:\Program Files (x86)`

The proper command should be `ed.exe "C:\Program Files\" exe`

**Comment by TheZoc** [comment] 2023-05-22 18:19
@Sanhuaitang when running from the command line and using a trailing slash, it works fine for me.
Can you confirm that is also working for you? :)

**Comment by bytimer** [comment] 2023-05-23 00:06
Yes ，searching path must have a trailing slash. 
 As what I said above, `"C:\Program Files\"`  will get the right results.  √
While `"C:\Program Files"` will contain C:\Program Files (x86), this is not right. ×

**Comment by TheZoc** [comment] 2023-05-23 20:14
The command line utility seems to work - and as I understand that should be a separate issue, relating to the script.
I added a new version that should fix the search path: https://github.com/TheZoc/EverythingDopus/releases/tag/v2.0-beta4

Please let me know if this works for you :)

**Comment by bytimer** [comment] 2023-05-24 15:48
Yes! all ok now ！Thahks very much！

**Closed as completed** 2023-09-13 21:27 UTC
